version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_local
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: carlos123
      MYSQL_DATABASE: security_jwt_db
      MYSQL_USER: root
      MYSQL_PASSWORD: carlos123
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:
